[phases.setup]
nixPkgs = ["nodejs_22", "pnpm", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm start"
