[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
phases = ["setup", "install", "build"]

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
